---
abstract: 'makes everything in your Perl code an RDF resource'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords:
  - Perl
  - RDF
  - SemWeb
  - 'Semantic Web'
  - UNIVERSAL
  - arrayref
  - class
  - hashref
  - scalar
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::Everywhere
name: RDF-Everywhere
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Data::UUID: 0
  Exporter: 0
  Moan: 0
  Object::ID: 0
  Pragmatic: 0
  RDF::Trine: 0
  Scalar::Util: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-Everywhere
  homepage: https://metacpan.org/release/RDF-Everywhere
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/RDF-Everywhere/
version: 0.002
